In [3]:
import matplotlib
matplotlib.use('TkAgg') # 'tkAgg' if Qt not present 
import matplotlib.pyplot as plt 
import scipy as sp
import matplotlib.animation as animation
  
class Pendulum:
    def __init__(self, theta1, theta2, dt):
        self.theta1 = theta1
        self.theta2 = theta2
          
        self.p1 = 0.0
        self.p2 = 0.0
          
        self.dt = dt
          
        self.g = 9.81
        self.length = 1.0
          
        self.trajectory = [self.polar_to_cartesian()]
  
    def polar_to_cartesian(self):
        x1 =  self.length * sp.sin(self.theta1)        
        y1 = -self.length * sp.cos(self.theta1)
          
        x2 = x1 + self.length * sp.sin(self.theta2)
        y2 = y1 - self.length * sp.cos(self.theta2)
         
        print(self.theta1, self.theta2)
        return sp.array([[0.0, 0.0], [x1, y1], [x2, y2]])
      
    def evolve(self):
        theta1 = self.theta1
        theta2 = self.theta2
        p1 = self.p1
        p2 = self.p2
        g = self.g
        l = self.length
         
        expr1 = sp.cos(theta1 - theta2)
        expr2 = sp.sin(theta1 - theta2)
        expr3 = (1 + expr2**2)
        expr4 = p1 * p2 * expr2 / expr3
        expr5 = (p1**2 + 2 * p2**2 - p1 * p2 * expr1) \
        * sp.sin(2 * (theta1 - theta2)) / 2 / expr3**2
        expr6 = expr4 - expr5
         
        self.theta1 += self.dt * (p1 - p2 * expr1) / expr3
        self.theta2 += self.dt * (2 * p2 - p1 * expr1) / expr3
        self.p1 += self.dt * (-2 * g * l * sp.sin(theta1) - expr6)
        self.p2 += self.dt * (    -g * l * sp.sin(theta2) + expr6)
         
        new_position = self.polar_to_cartesian()
        self.trajectory.append(new_position)
        print(new_position)
        return new_position
 
 
class Animator:
    def __init__(self, pendulum, draw_trace=False):
        self.pendulum = pendulum
        self.draw_trace = draw_trace
        self.time = 0.0
  
        # set up the figure
        self.fig, self.ax = plt.subplots()
        self.ax.set_ylim(-2.5, 2.5)
        self.ax.set_xlim(-2.5, 2.5)
  
        # prepare a text window for the timer
        self.time_text = self.ax.text(0.05, 0.95, '', 
            horizontalalignment='left', 
            verticalalignment='top', 
            transform=self.ax.transAxes)
  
        # initialize by plotting the last position of the trajectory
        self.line, = self.ax.plot(
            self.pendulum.trajectory[-1][:, 0], 
            self.pendulum.trajectory[-1][:, 1], 
            marker='o')
          
        # trace the whole trajectory of the second pendulum mass
        if self.draw_trace:
            self.trace, = self.ax.plot(
                [a[2, 0] for a in self.pendulum.trajectory],
                [a[2, 1] for a in self.pendulum.trajectory])
     
    def advance_time_step(self):
        while True:
            self.time += self.pendulum.dt
            yield self.pendulum.evolve()
             
    def update(self, data):
        self.time_text.set_text('Elapsed time: {:6.2f} s'.format(self.time))
         
        self.line.set_ydata(data[:, 1])
        self.line.set_xdata(data[:, 0])
         
        if self.draw_trace:
            self.trace.set_xdata([a[2, 0] for a in self.pendulum.trajectory])
            self.trace.set_ydata([a[2, 1] for a in self.pendulum.trajectory])
        return self.line,
     
    def animate(self):
        self.animation = animation.FuncAnimation(self.fig, self.update,
                         self.advance_time_step, interval=25, blit=False)
 
pendulum = Pendulum(theta1=sp.pi, theta2=sp.pi - 0.01, dt=0.01)
animator = Animator(pendulum=pendulum, draw_trace=True)
animator.animate()
plt.show()

C:\Users\HP\AppData\Local\Temp\ipykernel_27924\4220107901.py:23: DeprecationWarning: scipy.sin is deprecated and will be removed in SciPy 2.0.0, use numpy.sin instead
  x1 =  self.length * sp.sin(self.theta1)
C:\Users\HP\AppData\Local\Temp\ipykernel_27924\4220107901.py:24: DeprecationWarning: scipy.cos is deprecated and will be removed in SciPy 2.0.0, use numpy.cos instead
  y1 = -self.length * sp.cos(self.theta1)
C:\Users\HP\AppData\Local\Temp\ipykernel_27924\4220107901.py:26: DeprecationWarning: scipy.sin is deprecated and will be removed in SciPy 2.0.0, use numpy.sin instead
  x2 = x1 + self.length * sp.sin(self.theta2)
C:\Users\HP\AppData\Local\Temp\ipykernel_27924\4220107901.py:27: DeprecationWarning: scipy.cos is deprecated and will be removed in SciPy 2.0.0, use numpy.cos instead
  y2 = y1 - self.length * sp.cos(self.theta2)
C:\Users\HP\AppData\Local\Temp\ipykernel_27924\4220107901.py:30: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy

3.141592653589793 3.1315926535897933


C:\Users\HP\AppData\Local\Temp\ipykernel_27924\4220107901.py:40: DeprecationWarning: scipy.cos is deprecated and will be removed in SciPy 2.0.0, use numpy.cos instead
  expr1 = sp.cos(theta1 - theta2)
C:\Users\HP\AppData\Local\Temp\ipykernel_27924\4220107901.py:41: DeprecationWarning: scipy.sin is deprecated and will be removed in SciPy 2.0.0, use numpy.sin instead
  expr2 = sp.sin(theta1 - theta2)
C:\Users\HP\AppData\Local\Temp\ipykernel_27924\4220107901.py:45: DeprecationWarning: scipy.sin is deprecated and will be removed in SciPy 2.0.0, use numpy.sin instead
  * sp.sin(2 * (theta1 - theta2)) / 2 / expr3**2
C:\Users\HP\AppData\Local\Temp\ipykernel_27924\4220107901.py:50: DeprecationWarning: scipy.sin is deprecated and will be removed in SciPy 2.0.0, use numpy.sin instead
  self.p1 += self.dt * (-2 * g * l * sp.sin(theta1) - expr6)
C:\Users\HP\AppData\Local\Temp\ipykernel_27924\4220107901.py:51: DeprecationWarning: scipy.sin is deprecated and will be removed in SciPy 2.0.0, use numpy

3.141592653589793 3.1315926535897933
[[0.00000000e+00 0.00000000e+00]
 [1.22464680e-16 1.00000000e+00]
 [9.99983333e-03 1.99995000e+00]]
3.1416024619550025 3.1315730358784974
[[ 0.00000000e+00  0.00000000e+00]
 [-9.80836521e-06  1.00000000e+00]
 [ 1.00096417e-02  1.99994980e+00]]
3.1416220786719276 3.131533800473255
[[ 0.00000000e+00  0.00000000e+00]
 [-2.94250821e-05  1.00000000e+00]
 [ 1.00292584e-02  1.99994941e+00]]
3.1416515421917035 3.1314748896896107
[[ 0.00000000e+00  0.00000000e+00]
 [-5.88886019e-05  9.99999998e-01]
 [ 1.00587027e-02  1.99994881e+00]]
3.1416909294292044 3.131396188142482
[[ 0.00000000e+00  0.00000000e+00]
 [-9.82758393e-05  9.99999995e-01]
 [ 1.00980129e-02  1.99994801e+00]]
3.1417403558935955 3.131297522559496
[[ 0.00000000e+00  0.00000000e+00]
 [-1.47702303e-04  9.99999989e-01]
 [ 1.01472469e-02  1.99994699e+00]]
3.14179997595028 3.1311786614065427
[[ 0.00000000e+00  0.00000000e+00]
 [-2.07322359e-04  9.99999979e-01]
 [ 1.02064816e-02  1.99994575e+00]]
3.14

3.2167944913302473 3.0086061125792214
[[ 0.          0.        ]
 [-0.07513098  0.99717367]
 [ 0.05746392  1.98834399]]
3.221335977534431 3.0015814070185876
[[ 0.          0.        ]
 [-0.07965884  0.99682219]
 [ 0.05989541  1.98703661]]
3.2261229906152225 2.994192601682351
[[ 0.          0.        ]
 [-0.08442971  0.99642944]
 [ 0.06243717  1.9855857 ]]
3.231165976896001 2.986424330340629
[[ 0.          0.        ]
 [-0.08945359  0.99599099]
 [ 0.06509281  1.98397652]]
3.2364754056928753 2.978261147001296
[[ 0.          0.        ]
 [-0.09474045  0.99550201]
 [ 0.06786582  1.98219304]]
3.2420616992741422 2.9696876193363053
[[ 0.          0.        ]
 [-0.10030011  0.99495723]
 [ 0.07075951  1.98021791]]
3.2479351542127604 2.9606884336267907
[[ 0.          0.        ]
 [-0.10614218  0.99435096]
 [ 0.07377693  1.97803237]]
3.2541058544541115 2.951248510723312
[[ 0.          0.        ]
 [-0.11227596  0.99367706]
 [ 0.07692087  1.97561625]]
3.2605835767747746 2.9413531320210207
[[ 0.   

4.188002648459459 1.3030356221756259
[[ 0.          0.        ]
 [-0.86563136  0.50068189]
 [ 0.09873441  0.23610929]]
4.206249295822914 1.2656422303533772
[[ 0.          0.        ]
 [-0.87462252  0.48480455]
 [ 0.07917815  0.18436439]]
4.224988076461946 1.228680344338639
[[ 0.          0.        ]
 [-0.88355308  0.46833103]
 [ 0.05849382  0.13284984]]
4.244321686884421 1.1921355939842821
[[ 0.          0.        ]
 [-0.89244192  0.4511623 ]
 [ 0.03671865  0.08148589]]
4.26434790924488 1.1559472052858377
[[ 0.          0.        ]
 [-0.90129744  0.43320079]
 [ 0.0138797   0.03014893]]
4.285157376916667 1.1200067738509942
[[ 0.          0.        ]
 [-0.91011633  0.41435283]
 [-0.01001294 -0.02132352]]
4.306832999134482 1.0841608547083794
[[ 0.          0.        ]
 [-0.91888319  0.3945297 ]
 [-0.03497189 -0.07312489]]
4.329451112106783 1.0482173318634787
[[ 0.          0.        ]
 [-0.92757091  0.37364716]
 [-0.06103607 -0.12546943]]
4.353084113123862 1.0119551747539046
[[ 0.        

8.249295203490743 -1.0824701011316817
[[ 0.          0.        ]
 [ 0.92287585  0.38509759]
 [ 0.03975651 -0.08405081]]
8.309231843932942 -1.0317063574597836
[[ 0.          0.        ]
 [ 0.89815104  0.43968705]
 [ 0.03997484 -0.07366818]]
8.368315396311147 -0.9805392862007387
[[ 0.          0.        ]
 [ 0.87062067  0.49195492]
 [ 0.03982303 -0.06461967]]
8.426549794249205 -0.929044100247009
[[ 0.          0.        ]
 [ 0.84051234  0.5417924 ]
 [ 0.03946423 -0.05680757]]
8.483946019746638 -0.8772822558706351
[[ 0.          0.        ]
 [ 0.80804849  0.58911598]
 [ 0.03904407 -0.05012748]]
8.540520996680586 -0.8253036921775707
[[ 0.          0.        ]
 [ 0.77344422  0.63386437]
 [ 0.0386904  -0.04446948]]
8.59629660093398 -0.7731488144744552
[[ 0.          0.        ]
 [ 0.73690563  0.67599563]
 [ 0.03851328 -0.03971948]]
8.651298783413385 -0.7208502309133915
[[ 0.          0.        ]
 [ 0.69862876  0.71548435]
 [ 0.03860512 -0.03576048]]
8.705556799882743 -0.668434257260518
[[ 0.

12.566525619411408 3.1678870127347
[[ 0.00000000e+00  0.00000000e+00]
 [ 1.55005052e-04 -9.99999988e-01]
 [-2.61363242e-02 -3.45664731e-04]]
12.645422155634819 3.240667646713971
[[ 0.          0.        ]
 [ 0.07896923 -0.99687705]
 [-0.01994376 -0.00178097]]
12.724365529922025 3.31369562160917
[[ 0.          0.        ]
 [ 0.15733841 -0.98754475]
 [-0.01391621 -0.00231794]]
12.803266326609785 3.3869114681240635
[[ 0.          0.        ]
 [ 0.23468617 -0.97207119]
 [-0.00817943 -0.00201125]]
12.882036168116063 3.460257685477669
[[ 0.00000000e+00  0.00000000e+00]
 [ 3.10449209e-01 -9.50589969e-01]
 [-2.84987301e-03 -9.35460379e-04]]
12.960588519046938 3.533679611534521
[[ 0.00000000e+00  0.00000000e+00]
 [ 3.84086200e-01 -9.23297239e-01]
 [ 1.96836781e-03  8.16370302e-04]]
13.0388394542512 3.607126230959263
[[ 0.          0.        ]
 [ 0.45508604 -0.89044747]
 [ 0.00618638  0.0031347 ]]
13.116708375913783 3.680550902078643
[[ 0.          0.        ]
 [ 0.52297515 -0.85234793]
 [ 0.009

16.04773764236743 7.701959486917235
[[ 0.          0.        ]
 [-0.33327437  0.94282988]
 [ 0.6551925   0.79139262]]
16.058290238139897 7.734172771797622
[[ 0.          0.        ]
 [-0.34320494  0.93926055]
 [ 0.64962656  0.8197381 ]]
16.068478324321017 7.765338262282566
[[ 0.          0.        ]
 [-0.35275623  0.93571526]
 [ 0.64331752  0.84718793]]
16.07834985699858 7.79547443294693
[[ 0.          0.        ]
 [-0.36197583  0.93218748]
 [ 0.63631311  0.87371365]]
16.087951193473913 7.824599096575631
[[ 0.          0.        ]
 [-0.37090926  0.92866911]
 [ 0.62865911  0.8992908 ]]
16.097327085368228 7.85272939436057
[[ 0.          0.        ]
 [-0.37959993  0.92515074]
 [ 0.62039929  0.9238985 ]]
16.106520684830492 7.879881803588379
[[ 0.          0.        ]
 [-0.38808923  0.9216218 ]
 [ 0.61157538  0.94751908]]
16.115573561173854 7.906072160640796
[[ 0.          0.        ]
 [-0.39641654  0.91807076]
 [ 0.60222705  0.97013774]]
16.12452572563266 7.93131569729381
[[ 0.          0.

17.556455548966834 8.60320148634282
[[ 0.          0.        ]
 [-0.96168962 -0.2741406 ]
 [-0.2294692   0.40692713]]
